import type { ReportOvertimeMeta, ReportOvertimeReceiptLine, ReportOvertimeSegment, ReportOvertimeTrace } from "../../shared/types/api";
import type { CompanyOvertimeRule, CompanySettings, TimeEntryType, UserContract } from "../../shared/types/models";
import { diffMinutes, formatLocalDay, parseLocalDay } from "../../shared/utils/time";
import { calculateWorkDurationMinutes } from "./time-entry-metrics-service";
import { getContractScheduledMinutesForDay } from "./user-contract-schedule";

type WorkReportEntry = {
  id: number;
  user_id: number;
  entry_type: TimeEntryType;
  entry_date: string;
  start_time: string | null;
  end_time: string | null;
};

function resolveContractForDay(contracts: UserContract[], day: string) {
  let match: UserContract | null = null;
  for (const contract of contracts) {
    if (contract.startDate <= day && (contract.endDate === null || contract.endDate >= day)) {
      if (!match || contract.startDate >= match.startDate) {
        match = contract;
      }
    }
  }
  return match;
}

function getWeekStart(day: string, firstDayOfWeek: number) {
  const parsed = parseLocalDay(day) ?? new Date();
  const currentWeekday = parsed.getDay();
  const deltaToStart = (currentWeekday - firstDayOfWeek + 7) % 7;
  const start = new Date(parsed);
  start.setDate(parsed.getDate() - deltaToStart);
  return formatLocalDay(start);
}

function getStandardRule(settings: CompanySettings) {
  return settings.overtime.rules.find((rule) => rule.category === "standard_overtime")
    ?? {
      id: "standard-overtime",
      category: "standard_overtime",
      triggerKind: "daily_overtime",
      afterHours: settings.overtime.dailyOvertimeThresholdHours,
      windowStart: null,
      windowEnd: null,
      multiplierPercent: 50,
      compensationType: "cash_or_time_off"
    } satisfies CompanyOvertimeRule;
}

function createSegments(baseMinutes: number, standardOvertimeMinutes: number, employeeChoiceMinutes: number, breakMinutes: number): ReportOvertimeSegment[] {
  const segments: ReportOvertimeSegment[] = [
    { kind: "base", minutes: baseMinutes, label: "Base" },
    { kind: "standard_overtime", minutes: standardOvertimeMinutes, label: "Overtime" },
    { kind: "employee_choice", minutes: employeeChoiceMinutes, label: "Choice zone" },
    { kind: "break", minutes: breakMinutes, label: "Break" }
  ];
  return segments.filter((segment) => segment.minutes > 0);
}

function buildReceiptLines(baseMinutes: number, standardOvertimeMinutes: number, employeeChoiceMinutes: number, breakMinutes: number, multiplierPercent: number, reviewState: ReportOvertimeMeta["reviewState"]): ReportOvertimeReceiptLine[] {
  const lines: ReportOvertimeReceiptLine[] = [];
  if (baseMinutes > 0) {
    lines.push({
      label: "Standard pay",
      minutes: baseMinutes,
      valueMinutes: baseMinutes,
      detail: "Base bucket"
    });
  }
  if (standardOvertimeMinutes > 0) {
    lines.push({
      label: `Overtime (+${multiplierPercent}%)`,
      minutes: standardOvertimeMinutes,
      valueMinutes: Math.round(standardOvertimeMinutes * (1 + multiplierPercent / 100)),
      detail: "Generated by overtime threshold"
    });
  }
  if (employeeChoiceMinutes > 0) {
    lines.push({
      label: `Choice zone (+${multiplierPercent}%)`,
      minutes: employeeChoiceMinutes,
      valueMinutes: Math.round(employeeChoiceMinutes * (1 + multiplierPercent / 100)),
      detail: reviewState === "needs_review" ? "Employee choice required" : "Employee-choice eligible"
    });
  }
  if (breakMinutes > 0) {
    lines.push({
      label: "Unpaid break",
      minutes: breakMinutes,
      valueMinutes: null,
      detail: "Excluded from paid time"
    });
  }
  return lines;
}

function buildSummary(baseMinutes: number, standardOvertimeMinutes: number, employeeChoiceMinutes: number, weeklyOnlyOvertimeMinutes: number) {
  if (employeeChoiceMinutes > 0) {
    return "Employee choice zone reached";
  }
  if (weeklyOnlyOvertimeMinutes > 0) {
    return "Weekly overtime triggered";
  }
  if (standardOvertimeMinutes > 0) {
    return "Daily overtime triggered";
  }
  return baseMinutes > 0 ? "Within normal range" : "No paid work";
}

function buildTraces(
  settings: CompanySettings,
  dailyThresholdMinutes: number,
  weeklyThresholdMinutes: number,
  standardOvertimeMinutes: number,
  employeeChoiceMinutes: number,
  weeklyOvertimeMinutes: number
): ReportOvertimeTrace[] {
  const traces: ReportOvertimeTrace[] = [
    {
      title: `Rule set: ${settings.overtime.title}`,
      detail: `Daily threshold ${(dailyThresholdMinutes / 60).toFixed(1)}h, weekly threshold ${(weeklyThresholdMinutes / 60).toFixed(1)}h.`
    }
  ];

  if (standardOvertimeMinutes > 0) {
    traces.push({
      title: "Daily overtime",
      detail: `Worked time exceeded the daily overtime threshold and received the configured overtime premium.`
    });
  }
  if (weeklyOvertimeMinutes > 0) {
    traces.push({
      title: "Weekly overtime",
      detail: `This entry crossed the weekly threshold and contributed to weekly overtime.`
    });
  }
  if (employeeChoiceMinutes > 0) {
    traces.push({
      title: "Employee choice",
      detail: `The configured employee-choice zone was reached, so this entry should be reviewed for payout handling.`
    });
  }
  return traces;
}

function buildMeta(
  settings: CompanySettings,
  paidMinutes: number,
  rawMinutes: number,
  cumulativeWeekBefore: number,
  dailyThresholdMinutes: number,
  weeklyThresholdMinutes: number
): ReportOvertimeMeta {
  const standardRule = getStandardRule(settings);
  const choiceThresholdMinutes = settings.overtime.employeeChoiceAfterDailyHours === null
    ? Number.POSITIVE_INFINITY
    : Math.max(dailyThresholdMinutes, Math.round(settings.overtime.employeeChoiceAfterDailyHours * 60));
  const breakMinutes = Math.max(0, rawMinutes - paidMinutes);
  const standardDailyMinutes = Math.max(0, Math.min(paidMinutes, choiceThresholdMinutes) - dailyThresholdMinutes);
  const employeeChoiceMinutes = Number.isFinite(choiceThresholdMinutes)
    ? Math.max(0, paidMinutes - choiceThresholdMinutes)
    : 0;
  const baseMinutes = Math.max(0, paidMinutes - standardDailyMinutes - employeeChoiceMinutes);
  const cumulativeWeekAfter = cumulativeWeekBefore + paidMinutes;
  const weeklyOvertimeMinutes = Math.max(0, cumulativeWeekAfter - weeklyThresholdMinutes) - Math.max(0, cumulativeWeekBefore - weeklyThresholdMinutes);
  const weeklyOnlyOvertimeMinutes = Math.max(0, weeklyOvertimeMinutes - standardDailyMinutes - employeeChoiceMinutes);
  const multiplierPercent = standardRule.multiplierPercent;
  const equivalentValueMinutes = baseMinutes + Math.round((standardDailyMinutes + employeeChoiceMinutes) * (1 + multiplierPercent / 100));
  const reviewState: ReportOvertimeMeta["reviewState"] = employeeChoiceMinutes > 0
    || (settings.overtime.payoutDecisionMode === "conditional"
      && settings.overtime.employeeChoiceAfterWeeklyHours !== null
      && cumulativeWeekAfter > Math.round(settings.overtime.employeeChoiceAfterWeeklyHours * 60))
    ? "needs_review"
    : standardDailyMinutes > 0 || weeklyOvertimeMinutes > 0
      ? "overtime_only"
      : "none";
  const state: ReportOvertimeMeta["state"] = reviewState === "needs_review"
    ? "needs_review"
    : employeeChoiceMinutes > 0
      ? "employee_choice"
      : weeklyOnlyOvertimeMinutes > 0
        ? "weekly_overtime"
        : standardDailyMinutes > 0
          ? "daily_overtime"
          : "base_only";

  return {
    state,
    stateLabel: state === "needs_review"
      ? "Needs review"
      : state === "employee_choice"
        ? "Employee choice"
        : state === "weekly_overtime"
          ? "Weekly overtime"
          : state === "daily_overtime"
            ? "Daily overtime"
            : "Normal",
    reviewState,
    workedMinutes: rawMinutes,
    paidMinutes,
    breakMinutes,
    baseMinutes,
    standardOvertimeMinutes: standardDailyMinutes,
    employeeChoiceMinutes,
    weeklyOvertimeMinutes,
    weeklyOnlyOvertimeMinutes,
    equivalentValueMinutes,
    segments: createSegments(baseMinutes, standardDailyMinutes, employeeChoiceMinutes, breakMinutes),
    receiptLines: buildReceiptLines(baseMinutes, standardDailyMinutes, employeeChoiceMinutes, breakMinutes, multiplierPercent, reviewState),
    traces: buildTraces(settings, dailyThresholdMinutes, weeklyThresholdMinutes, standardDailyMinutes, employeeChoiceMinutes, weeklyOvertimeMinutes),
    summary: buildSummary(baseMinutes, standardDailyMinutes, employeeChoiceMinutes, weeklyOnlyOvertimeMinutes)
  };
}

export function buildOvertimeReportMeta(entries: WorkReportEntry[], settings: CompanySettings, contractsByUser: Map<number, UserContract[]>) {
  const byEntryId = new Map<number, ReportOvertimeMeta>();
  const workEntries = entries
    .filter((entry) => entry.entry_type === "work")
    .sort((left, right) => `${left.user_id}-${left.entry_date}-${left.start_time ?? ""}-${left.id}`.localeCompare(`${right.user_id}-${right.entry_date}-${right.start_time ?? ""}-${right.id}`));
  let currentUserId: number | null = null;
  let currentWeekKey = "";
  let cumulativeWeekMinutes = 0;

  for (const entry of workEntries) {
    const weekKey = `${entry.user_id}-${getWeekStart(entry.entry_date, settings.firstDayOfWeek)}`;
    if (currentUserId !== entry.user_id || currentWeekKey !== weekKey) {
      currentUserId = entry.user_id;
      currentWeekKey = weekKey;
      cumulativeWeekMinutes = 0;
    }

    const rawMinutes = diffMinutes(entry.start_time ?? "", entry.end_time);
    const paidMinutes = calculateWorkDurationMinutes(entry.start_time, entry.end_time, settings);
    const contracts = contractsByUser.get(entry.user_id) ?? [];
    const contract = resolveContractForDay(contracts, entry.entry_date);
    const contractDailyThresholdMinutes = contract ? Math.max(0, getContractScheduledMinutesForDay(contract, entry.entry_date)) : 0;
    const contractWeeklyThresholdMinutes = contract ? Math.max(0, Math.round(contract.hoursPerWeek * 60)) : 0;
    const dailyThresholdMinutes = contractDailyThresholdMinutes > 0
      ? contractDailyThresholdMinutes
      : Math.max(0, Math.round(settings.overtime.dailyOvertimeThresholdHours * 60));
    const weeklyThresholdMinutes = contractWeeklyThresholdMinutes > 0
      ? contractWeeklyThresholdMinutes
      : Math.max(0, Math.round(settings.overtime.weeklyOvertimeThresholdHours * 60));
    const meta = buildMeta(settings, paidMinutes, rawMinutes, cumulativeWeekMinutes, dailyThresholdMinutes, weeklyThresholdMinutes);
    byEntryId.set(entry.id, meta);
    cumulativeWeekMinutes += paidMinutes;
  }

  return byEntryId;
}

export function aggregateOvertimeMeta(items: ReportOvertimeMeta[]): ReportOvertimeMeta | null {
  if (items.length === 0) {
    return null;
  }

  const workedMinutes = items.reduce((sum, item) => sum + item.workedMinutes, 0);
  const paidMinutes = items.reduce((sum, item) => sum + item.paidMinutes, 0);
  const breakMinutes = items.reduce((sum, item) => sum + item.breakMinutes, 0);
  const baseMinutes = items.reduce((sum, item) => sum + item.baseMinutes, 0);
  const standardOvertimeMinutes = items.reduce((sum, item) => sum + item.standardOvertimeMinutes, 0);
  const employeeChoiceMinutes = items.reduce((sum, item) => sum + item.employeeChoiceMinutes, 0);
  const weeklyOvertimeMinutes = items.reduce((sum, item) => sum + item.weeklyOvertimeMinutes, 0);
  const weeklyOnlyOvertimeMinutes = items.reduce((sum, item) => sum + item.weeklyOnlyOvertimeMinutes, 0);
  const equivalentValueMinutes = items.reduce((sum, item) => sum + item.equivalentValueMinutes, 0);
  const reviewState: ReportOvertimeMeta["reviewState"] = items.some((item) => item.reviewState === "needs_review")
    ? "needs_review"
    : items.some((item) => item.reviewState === "overtime_only")
      ? "overtime_only"
      : "none";
  const state: ReportOvertimeMeta["state"] = reviewState === "needs_review"
    ? "needs_review"
    : employeeChoiceMinutes > 0
      ? "employee_choice"
      : weeklyOnlyOvertimeMinutes > 0
        ? "weekly_overtime"
        : standardOvertimeMinutes > 0
          ? "daily_overtime"
          : "base_only";

  return {
    state,
    stateLabel: state === "needs_review"
      ? "Needs review"
      : state === "employee_choice"
        ? "Employee choice"
        : state === "weekly_overtime"
          ? "Weekly overtime"
          : state === "daily_overtime"
            ? "Daily overtime"
            : "Normal",
    reviewState,
    workedMinutes,
    paidMinutes,
    breakMinutes,
    baseMinutes,
    standardOvertimeMinutes,
    employeeChoiceMinutes,
    weeklyOvertimeMinutes,
    weeklyOnlyOvertimeMinutes,
    equivalentValueMinutes,
    segments: createSegments(baseMinutes, standardOvertimeMinutes, employeeChoiceMinutes, breakMinutes),
    receiptLines: [
      { label: "Worked", minutes: workedMinutes, valueMinutes: paidMinutes, detail: "Paid minutes after breaks" },
      { label: "Base", minutes: baseMinutes, valueMinutes: baseMinutes, detail: "Normal bucket" },
      { label: "Overtime", minutes: standardOvertimeMinutes, valueMinutes: standardOvertimeMinutes, detail: "Daily overtime total" },
      { label: "Choice zone", minutes: employeeChoiceMinutes, valueMinutes: employeeChoiceMinutes, detail: "Needs payout review" }
    ].filter((line) => line.minutes > 0),
    traces: [
      { title: "Daily overflow", detail: `${Math.round(standardOvertimeMinutes / 60 * 10) / 10}h generated by daily thresholds.` },
      { title: "Weekly overflow", detail: `${Math.round(weeklyOnlyOvertimeMinutes / 60 * 10) / 10}h generated by weekly thresholds only.` }
    ].filter((trace) => !trace.detail.startsWith("0")),
    summary: buildSummary(baseMinutes, standardOvertimeMinutes, employeeChoiceMinutes, weeklyOnlyOvertimeMinutes)
  };
}
